spring:
  datasource:
    url: jdbc:mariadb://svc.sel5.cloudtype.app:30261/imageService?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB


