version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    environment:
      - SERVER_NAME=www.onoff.zone
    networks:
      - webnet
networks:
  webnet:
