version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./practice/build:/usr/share/nginx/html
      - ./practice/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./practice/data/certbot/conf:/etc/letsencrypt
      - ./practice/data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./practice/data/certbot/conf:/etc/letsencrypt
      - ./practice/data/certbot/www:/var/www/certbot
