version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./practice/data/certbot/conf:/etc/letsencrypt
      - ./practice/data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ./practice/data/certbot/conf:/etc/letsencrypt
      - ./practice/data/certbot/www:/var/www/certbot
