version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./practice/front/build:/usr/share/nginx/html
      - ./practice/front/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
