spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://maria:3306/products?createDatabaseIfNotExist=true
    url: jdbc:mariadb://3.37.91.99:3307/products?createDatabaseIfNotExist=true
    username: root
    password: qwer1234
  application:
    name: Product-Service
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  output:
    ansi:
      enabled: always


server:
  port: 12000

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    ip-address: 3.37.91.99

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://52.79.186.117:8761/eureka