
spring:
  jpa:
    ## spring jpa hibernate
    hibernate:
      ddl-auto: update
    show-sql: true
    ## database connect
  datasource:
    url: jdbc:mariadb://changuii_maria:3306/capstoneAuth?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

    # Spring boot 2.6버전 이후에 spring.mvc.pathmatch.matching-strategy 값이 ant_apth_matcher에서 path_pattern_parser로 변경되면서 몇몇 라이브러리에서 오류가 발생하고 있다!
    # https://goyunji.tistory.com/137
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
  application:
    name: User-Service
server:
  port: 11000
eureka:
  instance:
    instance-id: 52.79.186.117:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    ip-address: 52.79.186.117
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://52.79.186.117:8761/eureka


springboot:
  jwt:
    secret: secretKey123
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true
